version: "3"
services: 
    app: 
      container_name: swaerotimes
      restart: always
      build: .
      ports:
        - "80:80"
      links:
        - mongo_swaerotimes
    mongo_swaerotimes: 
      container_name: mongo_swaerotimes
      image: mongo
      volumes:
        - ./data:/data/db
      ports: 
        - "27017:27017"